{{- if eq .Values.storageclass "localstorage" }}
apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ .Values.Project }}-pv
  labels:
    type: local
spec:
  capacity:
    storage: {{ .Values.PVSize }}
  persistentVolumeReclaimPolicy: Retain
  accessModes:
  - ReadWriteMany
  hostPath:
    path: {{ .Values.PVDirectory }}
{{- end }}
